In [1]:
#prezicera nivelului apei in cm a Lacului Beleu

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_excel('beleu_regim_hidrologic.xlsx')
df

Ziua  Regimul hidrologic in cm
0    2015-01-01                       198
1    2015-01-02                       193
2    2015-01-03                       189
3    2015-01-04                       185
4    2015-01-05                       181
...         ...                       ...
2187 2020-12-27                        69
2188 2020-12-28                        69
2189 2020-12-29                        69
2190 2020-12-30                        71
2191 2020-12-31                        73

[2192 rows x 2 columns]

In [4]:
# creem variabile pentru prezicerea in zile a viitorului
projection = 365
#creem coloana care prezicem
df['Prezicere'] = df[['Regimul hidrologic in cm']].shift(-projection)
#vedem rezultatul
df

Ziua  Regimul hidrologic in cm  Prezicere
0    2015-01-01                       198       38.0
1    2015-01-02                       193       38.0
2    2015-01-03                       189       38.0
3    2015-01-04                       185       38.0
4    2015-01-05                       181       38.0
...         ...                       ...        ...
2187 2020-12-27                        69        NaN
2188 2020-12-28                        69        NaN
2189 2020-12-29                        69        NaN
2190 2020-12-30                        71        NaN
2191 2020-12-31                        73        NaN

[2192 rows x 3 columns]

In [5]:
#creem data setul independent (x)
X = np.array(df[['Regimul hidrologic in cm']])
#stergem ultimele 365 rinduri
X = X[:-projection]
print(X)

[[198]
 [193]
 [189]
 ...
 [ 39]
 [ 39]
 [ 39]]


In [6]:
#creem un data set (y)
y = df['Prezicere'].values
y = y[:-projection]
print(y)

[38. 38. 38. ... 69. 71. 73.]


In [8]:
# despartim datele in 85% antrenare si 15% antrenare
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= .365)

In [9]:
#creem un model de antrenare
linReg = LinearRegression()
#antrenam modelul
linReg.fit(X_train, y_train)

LinearRegression()

In [10]:
#testam modelul folosind scorul
linReg_confidence = linReg.score(X_test, y_test)
print('Linear regression Confidence:', linReg_confidence)

Linear regression Confidence: 0.11179643751215862


In [11]:
#creem o variabila x_projection pentru ultimele 365 de rinduri din data setul original
x_projection = np.array(df[['Regimul hidrologic in cm']])[-projection:]
print(x_projection)

[[ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 38]
 [ 38]
 [ 38]
 [ 38]
 [ 38]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 35]
 [ 35]
 [ 35]
 [ 35]
 [ 34]
 [ 34]
 [ 34]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 32]
 [ 32]
 [ 32]
 [ 32]
 [ 32]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 30]
 [ 30]
 [ 30]
 [ 32]
 [ 33]
 [ 35]
 [ 37]
 [ 40]
 [ 44]
 [ 48]
 [ 55]
 [ 59]
 [ 60]
 [ 61]
 [ 64]
 [ 69]
 [ 70]
 [ 72]
 [ 81]
 [ 85]
 [ 93]
 [ 97]
 [101]
 [115]
 [120]
 [121]
 [121]
 [121]
 [121]
 [119]
 [117]
 [102]
 [ 94]
 [ 82]
 [ 79]
 [ 75]
 [ 71]
 [ 68]
 [ 62]
 [ 53]
 [ 48]
 [ 47]
 [ 44]
 [ 41]
 [ 39]
 [ 38]
 [ 37]
 [ 35]
 [ 35]
 [ 32]
 [ 30]
 [ 29]
 [ 29]
 [ 28]
 [ 28]
 [ 26]
 [ 25]
 [ 24]
 [ 23]
 [ 20]
 [ 20]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 20]
 [ 20]
 [ 21]
 [ 22]
 [ 22]
 [ 22]
 [ 23]
 [ 23]
 [ 23]
 [ 23]
 [ 23]
 [ 24]
 [ 24]
 [ 26]
 [ 26]
 [ 28]
 [ 28]
 [ 28]
 [ 29]
 [ 29]
 [ 29]
 [ 30]
 [ 31]
 [ 31]
 [ 32]

In [12]:
# afisam prezicerea pentru pentru urm 365 zile
linReg_prediction = linReg.predict(x_projection)
print(linReg_prediction)

[ 82.97459009  82.97459009  82.97459009  82.97459009  82.97459009
  82.97459009  82.97459009  82.97459009  82.97459009  82.97459009
  82.59443923  82.59443923  82.59443923  82.59443923  82.59443923
  82.21428837  82.21428837  82.21428837  82.21428837  82.21428837
  82.21428837  81.83413751  81.83413751  81.83413751  81.83413751
  81.83413751  81.83413751  81.45398664  81.45398664  81.45398664
  81.45398664  81.07383578  81.07383578  81.07383578  80.69368492
  80.69368492  80.69368492  80.69368492  80.69368492  80.69368492
  80.31353406  80.31353406  80.31353406  80.31353406  80.31353406
  79.93338319  79.93338319  79.93338319  79.93338319  79.93338319
  79.93338319  79.55323233  79.55323233  79.55323233  80.31353406
  80.69368492  81.45398664  82.21428837  83.35474095  84.8753444
  86.39594785  89.05700389  90.57760734  90.9577582   91.33790906
  92.47836165  94.37911596  94.75926682  95.51956855  98.94092631
 100.46152976 103.50273666 105.0233401  106.54394355 111.86605563
 113.766809